services:
  frontend:
    image: helloardanish/environment-management-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    image: helloardanish/environment-management-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - ALLOWED_ORIGINS=http://192.168.189.82,http://192.168.189.82:80,http://localhost,http://localhost:80
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: system
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
      # - /Users/helloardanish/Documents/.../:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: system
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb-data: